Repository PolicyEngine/policyengine-uk, pull requests merged in 2021-09, with the labels that each got.

#133 Fix /api bug
  server/app.py
Labels: bugfix

#134 Actually fix /faq issue
  Makefile
  server/app.py
Labels: bugfix

#137 Fix social preview
  client/public/index.html
Labels: bugfix

#139 Link to demo video
  client/public/faq.md
Labels: documentation

#166 Fix benefit allocation bug and update version
  client/src/js/pages/situation/default_situation.js
  server/app.py
Labels: bugfix

#216 Update FAQ to reflect new FRS
  client/public/faq.md
Labels: documentation

#217 Add land value to household inputs
  client/src/js/pages/situation-results.jsx
  client/src/js/pages/situation-results/results.jsx
  client/src/js/pages/situation/default_situation.js
  policy_engine/app.py
  policy_engine/simulation/reforms.py
  policy_engine/simulation/situations.py
  policy_engine/situations/charts.py
Labels: household

#240 Fix bug which neutralised thresholds
  policy_engine_uk/app.py
  policy_engine_uk/simulation/parameters.yaml
  setup.py
Labels: bugfix

#248 Fix LVT parameter
  policy_engine_uk/simulation/parameters.yaml
Labels: bugfix

#249 Fix floating point notation
  policy_engine_uk/simulation/parameters.yaml
Labels: bugfix

#250 Bump version
  policy_engine_uk/app.py
  setup.py
Labels: bugfix

#251 Fix UC parameters
  client/src/js/pages/policy/default_policy.js
  policy_engine_uk/app.py
Labels: bugfix

#256 Legacy benefits
  Dockerfile
  Makefile
  client/src/js/pages/policy/controls.jsx
  client/src/js/pages/policy/default_policy.js
  policy_engine_uk/populations/metrics.py
  policy_engine_uk/simulation/parameters.yaml
  policy_engine_uk/situations/charts.py
  setup.py
  tests/server/populations/test_population_metrics.py
Labels: policy

#259 Remove invalid dependency
  Makefile
Labels: bugfix

#260 Revert make changes
  Makefile
Labels: bugfix

#261 Fix order of Makefile lines
  Makefile
Labels: bugfix

#262 Remove openfisca-uk dependency
  Makefile
Labels: bugfix

#263 Restore old setup
  Dockerfile
  Makefile
  setup.py
Labels: bugfix
