Repository PolicyEngine/policyengine-uk, pull requests merged in 2022-03, with the labels that each got.

#533 Add production-based carbon emissions parameter
  CHANGELOG.md
  openfisca_uk/parameters/consumption/carbon/production/Production.yaml
  setup.py
Labels: parameters

#539 Simplify housing benefit and guarantee credit income variables
  CHANGELOG.md
  openfisca_uk/variables/finance/benefit/family/housing_benefit.py
  openfisca_uk/variables/finance/benefit/family/pension_credit.py
  setup.py
Labels: enhancement, code-health

#554 Fix push action
  .github/workflows/push.yml
  changelog.yaml
Labels: bug-fix

#555 Forecasting bugs
  changelog.yaml
  docs/book/model/tax_credits.ipynb
  docs/summary/VARIABLE_STATS.md
  openfisca_uk/parameters/benefit/additional_uprating.yaml
  openfisca_uk/parameters/poverty/absolute_poverty_threshold_ahc.yaml
  openfisca_uk/parameters/poverty/absolute_poverty_threshold_bhc.yaml
  openfisca_uk/parameters/tax/income_tax/rates/dividends.yaml
  openfisca_uk/parameters/tax/income_tax/rates/uk.yaml
  openfisca_uk/parameters/tax/national_insurance/class_1/rates/employee/additional.yaml
  openfisca_uk/parameters/tax/national_insurance/class_1/rates/employee/main.yaml
  openfisca_uk/parameters/tax/national_insurance/class_1/thresholds/primary_threshold.yaml
  openfisca_uk/parameters/tax/national_insurance/class_4/rates/additional.yaml
  openfisca_uk/parameters/tax/national_insurance/class_4/rates/main.yaml
  openfisca_uk/parameters/tax/national_insurance/class_4/thresholds/lower_profits_limit.yaml
  openfisca_uk/tools/simulation.py
  openfisca_uk/tools/tax_benefit_uprating.py
  openfisca_uk/variables/household/income/benefit.py
Labels: bug-fix
