Repository PolicyEngine/policyengine-uk, pull requests merged in 2025-02, with the labels that each got.

#1050 Fix Enabling labor supply elasticities has impact on no-reform
  .github/workflows/code_changes.yaml
  .github/workflows/versioning.yaml
  changelog_entry.yaml
Labels: bug

#1051 Add capital gains LSRs fix
  .github/workflows/code_changes.yaml
  .github/workflows/versioning.yaml
  policyengine_uk/variables/gov/hmrc/capital_gains_tax/responses.py
  policyengine_uk/variables/gov/simulation/labor_supply_response/labor_supply_response.py
Labels: bug

#1054 Edit age condition in universal childcare
  changelog_entry.yaml
  policyengine_uk/parameters/gov/dfe/universal_childcare_entitlement/max_age.yaml
  policyengine_uk/parameters/gov/dfe/universal_childcare_entitlement/min_age.yaml
  policyengine_uk/variables/gov/dfe/universal_childcare_entitlement/universal_childcare_entitlement_eligible.py
Labels: bug-fix

#1058 Add two-child limit reform
  changelog_entry.yaml
  policyengine_uk/parameters/gov/contrib/two_child_limit/age_exemption.yaml
  policyengine_uk/tests/policy/reforms/parametric/two_child_limit/age_exemption.yaml
  policyengine_uk/variables/gov/dwp/universal_credit/child_element/uc_individual_child_element.py
Labels: enhancement
