Repository PolicyEngine/policyengine-uk, pull requests merged in 2025-05, with the labels that each got.

#1116 Remove redundant ```weeks_per_year.yaml``` from extended childcare
  changelog_entry.yaml
  policyengine_uk/parameters/gov/dfe/extended_childcare_entitlement/weeks_per_year.yaml
Labels: bug-fix

#1118 Add hours usage variable to extended childcare program
  changelog_entry.yaml
  policyengine_uk/tests/policy/baseline/gov/dfe/extended_childcare_entitlement/extended_childcare_entitlement.yaml
  policyengine_uk/variables/gov/dfe/extended_childcare_entitlement/extended_childcare_entitlement.py
  policyengine_uk/variables/gov/dfe/extended_childcare_entitlement/maximum_extended_childcare_hours_usage.py
  setup.py
Labels: bug-fix

#1128 Backdate parameters to 2015
  changelog_entry.yaml
  policyengine_uk/system.py
Labels: enhancement

#1133 Remove remaining Pension Credit double-count of private pension income
  changelog_entry.yaml
  policyengine_uk/parameters/gov/dwp/pension_credit/guarantee_credit/earnings_sources.yaml
  policyengine_uk/parameters/gov/dwp/pension_credit/guarantee_credit/income.yaml
  policyengine_uk/parameters/gov/dwp/pension_credit/income/sources.yaml
  policyengine_uk/tests/policy/baseline/gov/dwp/pension_credit/pension_credit_income.yaml
  policyengine_uk/variables/gov/dwp/pension_credit/pension_credit_earnings.py
Labels: bug

#1137 Employer NI variables are interfering with behavioural responses
  .github/workflows/code_changes.yaml
  .github/workflows/pr_code_changes.yaml
  changelog_entry.yaml
  policyengine_uk/variables/contrib/policyengine/employer_ni/employer_ni_fixed_employer_cost_change.py
Labels: bug
